#!/bin/bash

./sendGetBack -number 100000 -outConfig "'ether.pcap': 'ether.json'"
./sendGetBack -number 10000 -outConfig "'ip4.pcap':'ip4.json'"
./sendGetBack -number 1000 -outConfig "'ip6.pcap':'ip6.json'"
./sendGetBack -number 100000 -outConfig "'ip4tcp.pcap':'ip4tcp.json'"
./sendGetBack -number 100000 -outConfig "'ip4tcpVlan.pcap':'ip4tcpVlan.json'"
./sendGetBack -number 1000000 -outConfig "'ip6tcp.pcap':'ip6tcp.json'"
./sendGetBack -number 10000 -outConfig "'ip4udp.pcap':'ip4udp.json'"
./sendGetBack -number 10000 -outConfig "'ip4udpVlan.pcap':'ip4udpVlan.json'"
./sendGetBack -number 1000 -outConfig "'ip6udp.pcap':'ip6udp.json'"
./sendGetBack -number 1000000 -outConfig "'ip4icmp.pcap':'ip4icmp.json'"
./sendGetBack -number 100000 -outConfig "'ip6icmp.pcap':'ip6icmp.json'"
./sendGetBack -number 1000 -outConfig "'arp.pcap':'arp.json'"
./sendGetBack -number 100 -outConfig "'vlanTag.pcap':'vlanTag.json'"
./sendGetBack -number 100 -outConfig "'arpVlan.pcap':'arpVlan.json'"
./sendGetBack -number 100 -outConfig "'config.pcap': 'config.json'"
./sendGetBack -number 100 -outConfig "'mix.pcap': 'mix.json'"
./sendGetBack -number 100 -outConfig "'pcap.pcap': 'pcap.json'"
