# Copyright 2017 Intel Corporation. 
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM fedora

# Update distribution
# RUN dnf update -y

# Install build tools
# RUN dnf install -y @development-tools

# RUN dnf -y install numactl-devel.x86_64; dnf clean all

# Install DPDK support packages.
# RUN dnf install -y tar libhugetlbfs-utils libpcap-devel kernel kernel-devel kernel-headers

CMD ["/bin/bash"]
