# Copyright 2018 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
SUBDIRS = main pattern

export GO_BUILD_TAGS += hyperscan_v4

include $(PATH_TO_MK)/intermediate.mk
