# Copyright 2017 Intel Corporation. 
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../../mk
IMAGENAME = yanff-test-separate
EXECUTABLES = test-separate-part1 test-separate-part2

include $(PATH_TO_MK)/leaf.mk
