# Copyright 2017 Intel Corporation. 
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../../mk
IMAGENAME = yanff-test-handle2
EXECUTABLES = test-handle2-part1 test-handle2-part2

include $(PATH_TO_MK)/leaf.mk
