# Copyright 2017 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
IMAGENAME = nff-go-stash
EXECUTABLES =  create_packet_example forwardingTestL3 send_fixed_number rw_example sendback

include $(PATH_TO_MK)/leaf.mk
