# Copyright 2017 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
IMAGENAME = yanff-stash
EXECUTABLES =  create_packet_example forwardingTestL3 send_fixed_number rw_example

include $(PATH_TO_MK)/leaf.mk
