# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = ENV.fetch('http_proxy', false)
    config.proxy.https    = ENV.fetch('https_proxy', false)
  end

  vm_group_size = ENV.fetch('VM_GROUP_SIZE', 2).to_i
  vm_total_number = ENV.fetch("VM_TOTAL_NUMBER", 2).to_i
  vm_links_number = ENV.fetch("VM_LINKS_NUMBER", 2).to_i

  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "4096"
    vb.cpus = 8
    (1..vm_links_number * 2).each do |j|
      vb.customize ["modifyvm", :id, "--nicpromisc#{j + 1}", "allow-all"]
    end
  end

$provision = <<SHELL
echo Installing system packages
sudo apt-get update
sudo apt-get install -y python make gcc git libnuma-dev libpcap0.8-dev libelf-dev

echo Unpacking Go language into /opt
(cd /opt; sudo sh -c 'curl -L -s https://redirector.gvt1.com/edgedl/go/go1.9.2.linux-amd64.tar.gz | tar zx')
mkdir go
echo export GOPATH=\\"'$HOME'\\"/go > .bash_login
echo export GOROOT=/opt/go >> .bash_login
echo export YANFF=\\"'$GOPATH'\\"/src/github.com/intel-go/yanff >> .bash_login
echo export PATH=\\"'$GOPATH'\\"/bin:\\"'$GOROOT'\\"/bin:\\"'$PATH'\\" >> .bash_login
. .bash_login

echo Downloading and building YANFF
go get -d -v github.com/intel-go/yanff
(cd \"$GOPATH\"/src/github.com/intel-go/yanff; make)

echo Setting up 1024 huge pages
sudo sh -c 'echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'
sudo sh -c 'echo vm.nr_hugepages=1024 >> /etc/sysctl.conf'

echo Binding ports to DPDK
bindports()
{
    sudo modprobe uio
    sudo insmod \"$YANFF\"/dpdk/dpdk-17.08/x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
    sudo \"$YANFF\"/dpdk/dpdk-17.08/usertools/dpdk-devbind.py --bind=igb_uio 00:08.0 00:09.0
}
bindports
declare -f bindports >> .bash_login
unbindports()
{
    sudo \"$YANFF\"/dpdk/dpdk-17.08/usertools/dpdk-devbind.py --bind=e1000 00:08.0 00:09.0
}
declare -f unbindports >> .bash_login
runpktgen()
{
    (cd \"$YANFF\"/dpdk; sudo ./pktgen -c 0xff -n 4 -- -P -m \"[1:2].0, [3:4].1\" -T)
    rc=$?; if [[ $rc == 0 ]]; then reset; fi
}
declare -f runpktgen >> .bash_login
SHELL

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell",
                      privileged: false,
                      inline: $provision

  # Define six YANFF VMs
  user = ENV.fetch('USER', "nouser")
  (0..vm_total_number - 1).each do |i|
    config.vm.define "yanff-#{i}" do |node|
      node.vm.hostname = "yanff-#{i}"

      # Create inter-VM connections only for VMs inside of one VM group
      if i + 1 < vm_total_number && (i + 1) % vm_group_size != 0
        # Define forward inter-VM virtual network links
        (1..vm_links_number).each do |j|
          node.vm.network "private_network",
                          auto_config: false,
                          virtualbox__intnet: "link-#{user}-#{i + 1}-#{j}"
        end
      end

      if i % vm_group_size != 0
        # Define backward inter-VM virtual network links
        (1..vm_links_number).each do |j|
          node.vm.network "private_network",
                          auto_config: false,
                          virtualbox__intnet: "link-#{user}-#{i}-#{j}"
        end
      end
    end
  end
end
