// Code generated by "stringer -type=AppType,TestType,TestStatus types.go"; DO NOT EDIT.

package test

import "strconv"

const _AppType_name = "TestAppGoTestAppPktgenTestAppApacheBenchmarkTestAppLatencyTestAppWrkBenchmark"

var _AppType_index = [...]uint8{0, 9, 22, 44, 58, 77}

func (i AppType) String() string {
	if i < 0 || i >= AppType(len(_AppType_index)-1) {
		return "AppType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AppType_name[_AppType_index[i]:_AppType_index[i+1]]
}

const _TestType_name = "TestTypeBenchmarkTestTypeScenarioTestTypeApacheBenchmarkTestTypeLatencyTestTypeWrkBenchmark"

var _TestType_index = [...]uint8{0, 17, 33, 56, 71, 91}

func (i TestType) String() string {
	if i < 0 || i >= TestType(len(_TestType_index)-1) {
		return "TestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestType_name[_TestType_index[i]:_TestType_index[i+1]]
}

const _TestStatus_name = "TestCreatedTestInitializedTestInvalidTestRunningTestReportedPassedTestReportedFailedTestTimedOutTestInterrupted"

var _TestStatus_index = [...]uint8{0, 11, 26, 37, 48, 66, 84, 96, 111}

func (i TestStatus) String() string {
	if i < 0 || i >= TestStatus(len(_TestStatus_index)-1) {
		return "TestStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestStatus_name[_TestStatus_index[i]:_TestStatus_index[i+1]]
}
