# Copyright 2017 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
IMAGENAME = steps
EXECUTABLES = genscripts step01 step02 step03 step04 step05 step06 step07 step08 step09 step10 step11
COMMON_FILES = common.go

include $(PATH_TO_MK)/leaf.mk
