# Copyright 2017 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
IMAGENAME = steps
EXECUTABLES = genscripts step1 step2 step3 step4 step5 step6 step7 step8 step9 step10 step11
COMMON_FILES = common.go

include $(PATH_TO_MK)/leaf.mk
