# Copyright 2017 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../mk
IMAGENAME = ngic-dp
EXECUTABLES = ngic_dp
#LDFLAGS=-ldflags "-X=main.DEBUG_LOG=true"

include $(PATH_TO_MK)/leaf.mk
