# Copyright 2017 Intel Corporation. 
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
IMAGENAME = yanff-performance
EXECUTABLES = perf_light perf_main perf_seq ipsec latency/latency-part1 latency/latency-stub sendback

include $(PATH_TO_MK)/leaf.mk
