# Copyright 2017 Intel Corporation. 
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
IMAGENAME = flowride
EXECUTABLES = flowride

#.PHONY: printvars
#printvars:
#	@$(foreach V,$(sort $(.VARIABLES)), $(if $(filter-out environment% default automatic, $(origin $V)),$(warning $V=$($V) ($(value $V)))))

include $(PATH_TO_MK)/leaf.mk

#all: printvars
all:
