# Copyright 2017 Intel Corporation. 
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../../mk
IMAGENAME = nfv-test-merge
EXECUTABLES = test-merge-part1 test-merge-part2

include $(PATH_TO_MK)/leaf.mk
