# Copyright 2017 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../mk
IMAGENAME = ngicdp
EXECUTABLES = ngicdp

include $(PATH_TO_MK)/leaf.mk
