# Copyright 2018 Intel Corporation.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

PATH_TO_MK = ../../../mk
IMAGENAME = lb
EXECUTABLES = lb

lb: lb.go ../config.go

include $(PATH_TO_MK)/leaf.mk
